/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/autotag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Autotag Job
         * @description 触发自动打标任务。
         */
        post: operations["create_autotag_job_v1_admin_autotag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/autotag/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Autotag Job
         * @description 查询任务状态。
         */
        get: operations["get_autotag_job_v1_admin_autotag__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/discoveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Discoveries
         * @description 列出 PendingDiscovery 记录。
         */
        get: operations["list_discoveries_v1_admin_discoveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/discoveries/{discovery_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Discovery
         * @description 批准发现 → 同步创建 IngestJob → 后台异步驱动入库管线。
         */
        post: operations["approve_discovery_v1_admin_discoveries__discovery_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/discoveries/{discovery_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Discovery
         * @description 拒绝发现。
         */
        post: operations["reject_discovery_v1_admin_discoveries__discovery_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_v1_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact Tags */
        get: operations["get_artifact_tags_v1_artifacts__artifact_id__tags_get"];
        /**
         * Set Tags Endpoint
         * @description 整体替换 artifact 的 tag 集合。
         */
        put: operations["set_tags_endpoint_v1_artifacts__artifact_id__tags_put"];
        /** Add Tag Endpoint */
        post: operations["add_tag_endpoint_v1_artifacts__artifact_id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}/tags/{tag_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tag Endpoint */
        delete: operations["delete_tag_endpoint_v1_artifacts__artifact_id__tags__tag_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Environment
         * @description 所有机器的最新快照，按扫描时间倒序。
         */
        get: operations["list_environment_v1_environment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/environment/installed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Installed Names
         * @description 扁平化所有机器上「已装」条目的 name，供 artifacts 列表打「已装」标记。
         *
         *     返回 ``{"mcp": [...], "plugin": [...], "skill": [...]}``（去重排序）。
         */
        get: operations["list_installed_names_v1_environment_installed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/environment/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Scan
         * @description 接收插件上报的扫描快照，按 machine upsert。
         */
        post: operations["submit_scan_v1_environment_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 返回服务健康状态。任何子检查失败不会拖垮整体响应。
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Ingest
         * @description 启动一个 ingest 任务。业务逻辑由 ingestion.pipeline 实现。
         */
        post: operations["create_ingest_v1_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingest Status
         * @description 查询 ingest 任务状态。
         */
        get: operations["get_ingest_status_v1_ingest__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend
         * @description 运行推荐管线并返回 top-k skill。
         *
         *     hot path：无需 auth；token 预算由上层（plugin）保证。
         *     业务模块在并行实现，这里 lazy import 以避免启动期循环依赖。
         */
        post: operations["recommend_v1_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description 分页列出 artifact（兼容旧 /v1/skills 名）。
         */
        get: operations["list_skills_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Skill
         * @description 查询单个 skill 详情。
         */
        get: operations["get_skill_v1_skills__skill_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Skill
         * @description 删除 skill。
         */
        delete: operations["delete_skill_v1_skills__skill_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Skill
         * @description 切换 skill 启停。
         */
        patch: operations["patch_skill_v1_skills__skill_id__patch"];
        trace?: never;
    };
    "/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description 列出所有 tag，附带每个 tag 关联的 artifact 数量。
         */
        get: operations["list_tags_v1_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_v1_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags/{tag_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_v1_tags__tag_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalRequest */
        ApprovalRequest: {
            /** Notes */
            notes?: string | null;
        };
        /** ApprovalResponse */
        ApprovalResponse: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Discovery Id */
            discovery_id: string;
            /** Ingest Job Id */
            ingest_job_id?: string | null;
        };
        /**
         * ArtifactTagAddRequest
         * @description 追加单个 tag。
         */
        ArtifactTagAddRequest: {
            /** Score */
            score?: number | null;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "manual" | "auto";
            /** Tag */
            tag: string;
        };
        /**
         * ArtifactTagAssignment
         * @description 单条 artifact → tag 关联。
         */
        ArtifactTagAssignment: {
            /** Score */
            score?: number | null;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "manual" | "auto";
            /** Tag */
            tag: string;
        };
        /**
         * ArtifactTagSetRequest
         * @description 整体替换某 artifact 的 tag 集合。
         */
        ArtifactTagSetRequest: {
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "manual" | "auto";
            /** Tags */
            tags?: string[];
        };
        /** ArtifactTagsResponse */
        ArtifactTagsResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Tags */
            tags: components["schemas"]["ArtifactTagAssignment"][];
        };
        /**
         * AutotagRequest
         * @description 触发自动打标的批量任务。
         */
        AutotagRequest: {
            /** Artifact Ids */
            artifact_ids?: string[] | null;
            /**
             * Background
             * @default true
             */
            background: boolean;
            /**
             * Max Tags Per Artifact
             * @default 3
             */
            max_tags_per_artifact: number;
            /**
             * Only Untagged
             * @default true
             */
            only_untagged: boolean;
        };
        /** AutotagResponse */
        AutotagResponse: {
            /** Artifacts Tagged */
            artifacts_tagged: number;
            /** Artifacts Total */
            artifacts_total: number;
            /** Error */
            error?: string | null;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /**
         * EnvironmentResponse
         * @description 所有上报过的机器，按 scanned_at 倒序。
         */
        EnvironmentResponse: {
            /** Machines */
            machines: components["schemas"]["EnvironmentSnapshotItem"][];
        };
        /**
         * EnvironmentScanRequest
         * @description 插件上报的本机扫描快照（scanner.py 的输出，env 已脱敏）。
         *
         *     用 extra=allow 接住 scanner 未来可能加的字段，避免版本耦合。
         */
        EnvironmentScanRequest: {
            /** Agents */
            agents?: {
                [key: string]: unknown;
            }[];
            /** Cwd */
            cwd?: string | null;
            /** Machine */
            machine: string;
            /** Scanned At */
            scanned_at?: string | null;
            /** Totals */
            totals?: {
                [key: string]: number;
            };
        } & {
            [key: string]: unknown;
        };
        /** EnvironmentScanResponse */
        EnvironmentScanResponse: {
            /** Machine */
            machine: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Total Mcp */
            total_mcp: number;
            /** Total Plugin */
            total_plugin: number;
            /** Total Skill */
            total_skill: number;
        };
        /** EnvironmentSnapshotItem */
        EnvironmentSnapshotItem: {
            /** Agent Count */
            agent_count: number;
            /** Machine */
            machine: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Total Mcp */
            total_mcp: number;
            /** Total Plugin */
            total_plugin: number;
            /** Total Skill */
            total_skill: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Embedder Loaded */
            embedder_loaded: boolean;
            /** Reranker Available */
            reranker_available: boolean;
            /** Skills Count */
            skills_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "error";
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Version */
            version: string;
        };
        /** IngestJobStatus */
        IngestJobStatus: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Job Id */
            job_id: string;
            /** Skills Added */
            skills_added: number;
            /** Skills Updated */
            skills_updated: number;
            /** Source Url */
            source_url: string;
            /** Status */
            status: string;
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Auto Approve
             * @default true
             */
            auto_approve: boolean;
            /**
             * Branch
             * @default main
             */
            branch: string;
            /**
             * Github Url
             * Format: uri
             */
            github_url: string;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** PendingDiscoveryItem */
        PendingDiscoveryItem: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "pending" | "approved" | "rejected";
            /**
             * Found At
             * Format: date-time
             */
            found_at: string;
            /** Found Via */
            found_via: string;
            /** Id */
            id: string;
            /** Sample Skill Names */
            sample_skill_names: string[];
            /** Skill Count */
            skill_count: number;
            /** Source Repo */
            source_repo: string;
            /** Source Stars */
            source_stars: number;
            /** Source Url */
            source_url: string;
        };
        /**
         * RecommendRequest
         * @description POST /v1/recommend 请求体。
         */
        RecommendRequest: {
            /** Agent */
            agent?: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /** Exclude Ids */
            exclude_ids?: string[];
            /**
             * Max Tokens
             * @default 4000
             */
            max_tokens: number;
            /** Prompt */
            prompt: string;
            /**
             * Top K
             * @default 3
             */
            top_k: number;
            /** Types */
            types?: ("skill" | "mcp" | "plugin")[] | null;
        };
        /** RecommendResponse */
        RecommendResponse: {
            /** Candidates Considered */
            candidates_considered: number;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Fallback Used */
            fallback_used: boolean;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Request Id */
            request_id: string;
        };
        /** Recommendation */
        Recommendation: {
            /**
             * Artifact Type
             * @default skill
             * @enum {string}
             */
            artifact_type: "skill" | "mcp" | "plugin";
            /** Body */
            body: string;
            /** Description */
            description: string;
            /** Mcp Config */
            mcp_config?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name: string;
            /** Plugin Manifest */
            plugin_manifest?: {
                [key: string]: unknown;
            } | null;
            /** Rerank Reason */
            rerank_reason?: string | null;
            /** Score */
            score: number;
            /** Skill Id */
            skill_id: string;
            /** Source Url */
            source_url: string;
            /** Tags */
            tags?: string[];
            /** Tokens */
            tokens: number;
        };
        /**
         * SkillBrief
         * @description 列表用的精简表示。
         */
        SkillBrief: {
            /**
             * Artifact Type
             * @default skill
             * @enum {string}
             */
            artifact_type: "skill" | "mcp" | "plugin";
            /** Body Tokens */
            body_tokens: number;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Recommend Count */
            recommend_count: number;
            /** Source Repo */
            source_repo: string;
            /** Source Stars */
            source_stars: number;
            /** Source Url */
            source_url: string;
            /** Tags */
            tags?: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkillDetail */
        SkillDetail: {
            /**
             * Artifact Type
             * @default skill
             * @enum {string}
             */
            artifact_type: "skill" | "mcp" | "plugin";
            /** Body */
            body: string;
            /** Body Tokens */
            body_tokens: number;
            /** Cluster Id */
            cluster_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Is Approved */
            is_approved: boolean;
            /** Last Recommended At */
            last_recommended_at: string | null;
            /** License */
            license: string | null;
            /** Mcp Config */
            mcp_config?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name: string;
            /** Plugin Manifest */
            plugin_manifest?: {
                [key: string]: unknown;
            } | null;
            /** Recommend Count */
            recommend_count: number;
            /** Source Path */
            source_path: string;
            /** Source Repo */
            source_repo: string;
            /** Source Stars */
            source_stars: number;
            /** Source Url */
            source_url: string;
            /** Tags */
            tags?: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkillListResponse */
        SkillListResponse: {
            /** Items */
            items: components["schemas"]["SkillBrief"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * SkillPatchRequest
         * @description PATCH /v1/skills/{id} 请求体。当前允许切换启停。
         */
        SkillPatchRequest: {
            /** Is Active */
            is_active: boolean;
        };
        /** TagCreateRequest */
        TagCreateRequest: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /** TagItem */
        TagItem: {
            /**
             * Artifact Count
             * @default 0
             */
            artifact_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Is Builtin */
            is_builtin: boolean;
            /** Name */
            name: string;
        };
        /** TagListResponse */
        TagListResponse: {
            /** Items */
            items: components["schemas"]["TagItem"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_autotag_job_v1_admin_autotag_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutotagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutotagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_autotag_job_v1_admin_autotag__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutotagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_discoveries_v1_admin_discoveries_get: {
        parameters: {
            query?: {
                decision?: string;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingDiscoveryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_discovery_v1_admin_discoveries__discovery_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discovery_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_discovery_v1_admin_discoveries__discovery_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discovery_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_v1_artifacts_get: {
        parameters: {
            query?: {
                q?: string | null;
                source_repo?: string | null;
                active?: boolean | null;
                type?: ("skill" | "mcp" | "plugin") | null;
                tag?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_tags_v1_artifacts__artifact_id__tags_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactTagsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tags_endpoint_v1_artifacts__artifact_id__tags_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactTagSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactTagsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_tag_endpoint_v1_artifacts__artifact_id__tags_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactTagAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactTagsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_endpoint_v1_artifacts__artifact_id__tags__tag_name__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                artifact_id: string;
                tag_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactTagsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_environment_v1_environment_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_installed_names_v1_environment_installed_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_scan_v1_environment_scan_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_ingest_v1_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingest_status_v1_ingest__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_v1_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_v1_skills_get: {
        parameters: {
            query?: {
                /** @description 按 name/description 模糊匹配 */
                q?: string | null;
                source_repo?: string | null;
                active?: boolean | null;
                /** @description 按 artifact 类型过滤 */
                type?: ("skill" | "mcp" | "plugin") | null;
                /** @description 按单个 tag 名过滤 */
                tag?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_v1_skills__skill_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_skill_v1_skills__skill_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_skill_v1_skills__skill_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_v1_tags_get: {
        parameters: {
            query?: {
                builtin_only?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_v1_tags_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_v1_tags__tag_name__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tag_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
